#!/bin/sh

set -o errexit
set -o nounset


# сохранение, если в 20с было одна операция
# --dir /data обязательно!, чтобы сохранялись данные, устанавливаем расположение dump.rdb
redis-server \
    --save 20 1 \
    --requirepass ${REDIS_PASSWORD} \
    --dir /data