version: '3.9'
services:
  inventory:
    build:
      context: .
      dockerfile: ./docker/fastapi/inventory/Dockerfile
    restart: on-failure
    volumes:
      - .:/var/www/fastapi
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - fastapi
  payment:
    build:
      context: .
      dockerfile: ./docker/fastapi/payment/Dockerfile
    restart: on-failure
    volumes:
      - .:/var/www/fastapi
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    networks:
      - fastapi
  redis:
    build: 
      dockerfile: ./docker/redis/Dockerfile
    env_file:
      - ./.env
    expose:
      - "6379"
    volumes:
      - redis_db:/data
    networks:
      - fastapi

volumes:
  redis_db:

networks:
  fastapi:
    driver: bridge
