#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


# Чтобы запускалось 2 процесса, скрипт помещается в CMD!

uvicorn inventory.main:app --host 0.0.0.0 --port 8000 --reload & 

python3 -m inventory.redis_consumer.py &

# Wait for any process to exit
wait -n

# Exit with status of process that exited first
exit $?