#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

uvicorn payment.main:app --host 0.0.0.0 --port 8001 --reload &

python3 -m payment.redis_consumer.py &

# Wait for any process to exit
wait -n

# Exit with status of process that exited first
exit $?